### PR TITLE
MathGame by VaZoi

### PR DESCRIPTION
**Pull request by VaZoi**

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @VaZoi,

This project requires you to create a math game, you have submitted a calculator application?

Have you submitted the wrong project? Or have you misunderstood the requirements?

[Project](https://thecsharpacademy.com/project/53/math-game)
[Tutorial - Visual Studio](https://www.youtube.com/watch?v=iLByqqLGYEc&list=PL4G0MUH8YWiD1p5ySamqNWAaWlnwp1Vip)
[Tutorial - Visual Studio Code](https://www.youtube.com/watch?v=nnDNeJX-uBE)

Thanks,
@chrisjamiecarter

**Comment by VaZoi** [comment]
Hi, @chrisjamiecarter 
Then I think I misunderstood the requirements and what I needed to build.

I am gonna check the video tutorial that was attached to the exercise.

**Comment by chrisjamiecarter** [comment]
Perfect, 

Please adjust, commit and push your changes, and then I will review.

Good luck 🤞 

Thanks,
@chrisjamiecarter

**Review by chrisjamiecarter — APPROVED** [review]
Hey @VaZoi,

Great submission! 🎉
Well done, especially pivoting and re-applying the correct requirements.

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter

**Pull request closed without merging**
