### PR TITLE
Project Done

### PR DESCRIPTION
**Pull request by Lycanthrope8**
Please review my project

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
Hi! Thanks for submitting! It looks like your project was already a repository itself so it was picked up as a subfolder. You can see what files were recognized by git in the "Filers Changed" tab: 

image

To fix this, remove the .git folder from inside your project folder (not the academy's folder), commit again and push 😁 Let me know if you have questions

**Comment by TheCSharpAcademy** [comment]
@Lycanthrope8 Let me know if you need help 🤓

**Comment by Lycanthrope8** [comment]
Okay. I deleted the .github repository and pushed it. Is it okay now??

**Comment by TheCSharpAcademy** [comment]
@Lycanthrope8 Not yet. It has to be **the .git folder**. You can alternatively submit the link to your own repo this time so I can review quickly 🤓

**Comment by Lycanthrope8** [comment]
Thanks you for this opportunity. here is my repo link : https://github.com/Lycanthrope8/ConsoleApps-MathGame

**Comment by TheCSharpAcademy** [comment]
@Lycanthrope8 Thanks for sending the link. I ran the project successfully but when I try a division, I get this. 😟Could you please fix it? 🤓
image

**Comment by Lycanthrope8** [comment]
image
Mine worked perfectly fine

**Comment by TheCSharpAcademy** [comment]
@Lycanthrope8 Judging by your screenshot, you're presenting a division that results in non-integers. Preventing that is a requirement. Please send a fix for that and I'll approve. 🫡
image

**Comment by Lycanthrope8** [comment]
I just checked. I fulfill this requirement. Will you please check again? 
My app does not present anything for which the answer will be na on integer. Every time the answers are integers.

**Comment by TheCSharpAcademy** [comment]
@Lycanthrope8  Project approved! 😄✅ Yup you were right, my bad, your app does show the correct divisions. It's a shame you didn't complete the challenges this time. 😟 It's always a good use of your time. But nothing stops you from revisiting the project later. 

🥋And congratulations! You got your green belt!! 🟩🟩

🔍I don't have much to say about the code, it's clean and tidy, you follow good principles (DRY, SoC). Well done! For future projects I do recommend you complete the challenges as well, it will take your knowledge to the next level.

👪Oh and if possible join our Discord Community and add your username to your profile so you can be part of the community as well. 😁

✋🏻Your next project will be a bit more challenging, as it involves SQL with ADO.NET. Let us know if you get stuck! Looking forward to seeing your code.

**Pull request closed without merging**
