### PR TITLE
built math game;

### PR DESCRIPTION
**Pull request by mekasu0124**

### CODE REVIEW

**Comment by mekasu0124** [comment]
Thank you for reviewing my code. I'm new to C# so the fact that I was able to do this was pretty awesome!

**Comment by TheCSharpAcademy** [comment]
@mekasu0124 Well done! Your code is clean and tidy. 😁

I found one minor issue (that wasn't part of the requirements). On the medium or hard division games, all equations result in 1. Try fixing this bug as an exercise 😊

image

**Comment by mekasu0124** [comment]
> @mekasu0124 Well done! Your code is clean and tidy. 😁
> 
> I found one minor issue (that wasn't part of the requirements). On the medium or hard division games, all equations result in 1. Try fixing this bug as an exercise 😊
> 
> image

I am currently working on this issue. I do apologize.

**Comment by mekasu0124** [comment]
> @mekasu0124 Well done! Your code is clean and tidy. 😁
> 
> I found one minor issue (that wasn't part of the requirements). On the medium or hard division games, all equations result in 1. Try fixing this bug as an exercise 😊
> 
> image

I have fixed this issue :) thank you again!

**Pull request merged**
