### PR TITLE
Retried Committing and pushing

### PR DESCRIPTION
**Pull request by JvR-Hannes**

### CODE REVIEW

**Comment by JvR-Hannes** [comment]
I have really enjoyed this challenge!! Took me a whole day to figure out but I managed to get to the end. Learned a bunch of new stuff.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@JvR-Hannes Thanks for submitting! 😁

At the moment the project doesn't build. Looks like there's something wrong with the GetName() method: 
image

Could you please fix it? 🙏🏻

**Comment by JvR-Hannes** [comment]
I have made the necessary changes

**Comment by TheCSharpAcademy** [comment]
@JvR-Hannes Well done! Project approved! 👌🏻🤓✅ And well done for completing some of the challenges! I recommend you always do that, as it pushes you and makes you learn faster.

And congratulations! You got your green belt!! 🟩🟩😄

Just one piece of feedback:  For future projects, make sure you remove unnecessary comments [as per our code conventions](https://thecsharpacademy.com/article/58/code-conventions) 🤓

See you in the next project 🤓

**Pull request closed without merging**
