### PR TITLE
Hassan math game

### PR DESCRIPTION
**Pull request by hassanyahya400**

### CODE REVIEW

**Comment by antonderegt** [comment]
Hey @hassanyahya400 did you also submit this project in the academy website?

**Comment by hassanyahya400** [comment]
I have not submitted it in the academy website, how can I do that?

**Comment by antonderegt** [comment]
> I have not submitted it in the academy website, how can I do that?

Go to the dashboard, click [submit project](https://thecsharpacademy.com/dashboard/submit-project), select the math game project and enter the url of this PR.

Once you do that, the reviewers get a notification and someone will pick it up 😄

**Comment by hassanyahya400** [comment]
Okay, thanks

Sincerely,
Hassan Yahya

**Comment by TheCSharpAcademy** [comment]
@hassanyahya400 @antonderegt  Closing the PR due to inactivity, plz reopen if needed 😊

**Pull request closed without merging**
