### PR TITLE
Now .git is only in main folder

### PR DESCRIPTION
**Pull request by Rutwik2005**
.git is only present in CodeReviews.Console.MathGame

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Rutwik2005 Thanks for submitting! It looks like there's some misunderstanding of the app's requirements. Users should be prompted with a mathematical question. Then the app should collect the user's answer for that question and evaluate if it's correct or not. At the moment you're simply returning operations: 
image

If you're confused check the video tutorial in the project's page https://www.thecsharpacademy.com/project/53/math-game. And don't hesitate to reach out if you have questions.

🗺️Don't forget you need to submit your Free Code Camp certificate to get your 🟩🟩 Green Belt. [You can see the requirements for each belt here](https://thecsharpacademy.com/dashboard/roadmap). 

Oh and if possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

**Comment by Rutwik2005** [comment]
Thank you for correcting me i have submitted the new code logic.

**Comment by TheCSharpAcademy** [comment]
@Rutwik2005 Project approved! 😄✅ It's a shame you didn't complete the challenges this time. 😟 It's always a good use of your time!  

And congratulations! You got your green belt!! 🟩🟩

For future projects I highly recommend you learn about the [DRY Principle (Don't Repeat Yourself) ](https://www.thecsharpacademy.com/article/30006/dry-principle-csharp)😢. It's the most important challenge in this project. You should be able to have all games using just one method.

Oh and if possible join our Discord Community and add your username [[to your profile](https://thecsharpacademy.com/dashboard/profile)](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

Looking forward to seeing your next projects! 😄

**Comment by Rutwik2005** [comment]
yes i will try  completing all the challenges next time.

**Pull request closed without merging**
