### PR TITLE
added Random Game Option;

### PR DESCRIPTION
**Pull request by mekasu0124**
I forgot to add the code for the random game option. I have just built, tested, and ran this. Thank you again for the review!

### CODE REVIEW

**Comment by mekasu0124** [comment]
I am currently working on the issue with Medium and Hard mode division giving the same number twice when pulling random numbers

**Comment by mekasu0124** [comment]
I fixed the issue of medium and hard difficulty showing the same first number and second number. Thank you again for the review!

**Comment by TheCSharpAcademy** [comment]
@mekasu0124 Let me know when you finish. I don't review the challenges (lack of time) but I'm happy to push it when it's ready

**Comment by mekasu0124** [comment]
> @mekasu0124 Let me know when you finish. I don't review the challenges (lack of time) but I'm happy to push it when it's ready

I'm ready for it. Apologies on the late response

**Comment by TheCSharpAcademy** [comment]
@mekasu0124 Well done on completing the challenges. The repository got too messy and hard to maintain and I'm not pushing code into it anymore, I'm just using it to review, so I'm closing the PR 😁

**Pull request closed without merging**
