### PR TITLE
Finished project.

### PR DESCRIPTION
**Pull request by alvaromosconi**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@alvaromosconi Hi there! Congratulations on finishing your project! I can't see it on our database, could you please submit it via the dashboard? 😊

**Comment by alvaromosconi** [comment]
Sorry I'm new to this. How do I do that? Do I have to redo the PR?

**Comment by alvaromosconi** [comment]
Hello. Thanks for the congratulations! How can I do it through the dashboard? I have to redo the PR?

**Comment by alvaromosconi** [comment]
> @alvaromosconi Hi there! Congratulations on finishing your project! I can't see it on our database, could you please submit it via the dashboard? 😊

Thanks! I hadn't realized that I had to do it on the TheC#Academy website, sorry.

**Pull request merged**
