### PR TITLE
All requirements + challenges completed.

### PR DESCRIPTION
**Pull request by empty-codes**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@empty-codes Have you submitted this project in the [Academy's dashboard](https://thecsharpacademy.com/dashboard/submit-project)? I can't see it there. 😟

**Comment by TheCSharpAcademy** [comment]
@empty-codes I saw you tried to submit a project to the academy but it didn't work correctly. Could you please try again? 🤓

**Comment by empty-codes** [comment]
> @empty-codes I saw you tried to submit a project to the academy but it didn't work correctly. Could you please try again? 🤓

Just did 😅. Thank you.

**Comment by TheCSharpAcademy** [comment]
@empty-codes Well done! Project approved! 👌🏻🤓✅ And well done for completing the challenges! I recommend you always do that, as it pushes you and makes you learn faster 😄

️Don't forget you need to submit your Free Code Camp certificate to get your 🟩🟩Green Belt. [You can see the requirements for each belt here](https://thecsharpacademy.com/dashboard/roadmap). 

For future projects, don't forget to remove unnecessary comments. Especially when they're generated by Chat GPT 🤖🤖Your code should be self-explanatory. You can find more information [in our code convention](https://thecsharpacademy.com/article/58/code-conventions). 

🧑Oh and if possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

**Pull request closed without merging**
