### PR TITLE
chore: pull request

### PR DESCRIPTION
**Pull request by Sakuraxx**

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@Sakuraxx hello! Did you submit this project in our platform? I can't see it in the database

**Comment by TheCSharpAcademy** [comment]
@Sakuraxx https://thecsharpacademy.com/ 😁😁

**Comment by Sakuraxx** [comment]
> @Sakuraxx https://thecsharpacademy.com/ 😁😁

Thanks! I submitted it.  The url I input was https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/124.  😁

**Comment by TheCSharpAcademy** [comment]
@Sakuraxx Well done! You're now a Green Belt 😊

For future reference, only comment when absolutely necessary. Your code should be self-explanatory 😁
image

**Comment by Sakuraxx** [comment]
> @Sakuraxx Well done! You're now a Green Belt 😊
> 
> For future reference, only comment when absolutely necessary. Your code should be self-explanatory 😁 image

THANKS!

**Pull request closed without merging**
