### PR TITLE
Finishe project

### PR DESCRIPTION
**Pull request by Parab3llum**
Had fun working on it

### CODE REVIEW

**Comment by edvaudin** [comment]
Hi! Congratulations on finishing your Math Game! Please can you review the Codacy Static Code Analysis feedback and ensure your code passes its tests first before I review your code.

If you need any help, please reach out to me on Discord (Xarvus)

**Comment by TheCSharpAcademy** [comment]
@Parab3llum Hey there! Let us know if you need any help?

**Comment by TheCSharpAcademy** [comment]
@Parab3llum We haven't heard from you in a while 😔

**Comment by TheCSharpAcademy** [comment]
@Parab3llum  I'm closing the PR as it's been reviewed more than a month ago, feel free to resubmit the project and reopen the PR if you'd like to proceed.

**Pull request closed without merging**
