### PR TITLE
Finished Math Game

### PR DESCRIPTION
**Pull request by masherishere**

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hi there. I realy enjoyed reviewing your project. You have used a model (Game class) to record each game  and you have multiple classes for different concerns. Good job.
I noticed that you are using a validation method to prevent division by zero in the helper class. And you are using this method in all of your game types. 
Since addition, substraction and multiplication does not need such a validation, it is better  to clear unnecessary code from their methods. Unnecessary code can lead to risk for mistakes, debugging problems, less readable and maintainable code.
You can make a seperate method to generate numbers for these operations.
Can you please clean addition,substraction and multiplication methods from unnecessary validation before i can approve your project?

image

**Comment by masherishere** [comment]
> Hi there. I realy enjoyed reviewing your project. You have used a model (Game class) to record each game and you have multiple classes for different concerns. Good job. I noticed that you are using a validation method to prevent division by zero in the helper class. And you are using this method in all of your game types. Since addition, substraction and multiplication does not need such a validation, it is better to clear unnecessary code from their methods. Unnecessary code can lead to risk for mistakes, debugging problems, less readable and maintainable code. You can make a seperate method to generate numbers for these operations. Can you please clean addition,substraction and multiplication methods from unnecessary validation before i can approve your project?
> 
> image


Sure, I will  create another separate helper method to generate random number for addition, substraction and multiplication, thanks for the feedback.

**Comment by masherishere** [comment]
Hi @Doc415 , 
I already create new static method on helpers called GetRandomNumbers to get random number for addtion, substraction & multiplication

**Review by Doc415 — APPROVED** [review]
Thanks for updating your project. I am approving it now.
Waiting to see your next project.Good job!

PS: You can reconsider to rename your array variable divisionNumbers in other operations. It may be confusing when you need to come back to your code.

**Comment by masherishere** [comment]
Thankyou for approving my PR

**Pull request closed without merging**
