### PR TITLE
Added math game project

### PR DESCRIPTION
**Pull request by RyanMStaudacher**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@RyanMStaudacher Thanks for submitting! 🫡 At the moment I can't get past the menu. 😟Could you please fix it and commit your changes? This will update the pull request 👌🏻
image

**Comment by RyanMStaudacher** [comment]
@TheCSharpAcademy Should be working now

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@RyanMStaudacher Thanks for making the changes! It does work. However I think you misunderstood the requirements. 😔

Your program is a calculator works well as a calculator 👌🏻, but it should be a game. Users should get presented with a few mathematical questions ⁉️. Upon answering the questions users get given a score based on how many questions they got right. 💯

I hope that makes sense? Let me know if you have questions. 🫡

**Comment by RyanMStaudacher** [comment]
@TheCSharpAcademy Woops, got a little confused by the phrasing on that one, thanks for letting me know! I've updated the project to be a game now instead of just a calculator. I've also added the functionality to choose a random operation. Hopefully that is working like it should now.

**Comment by TheCSharpAcademy** [comment]
@RyanMStaudacher Project approved! 😄✅ And well done for completing the challenges! I recommend you always do that, as it pushes you and makes you learn faster. 

🗺️Don't forget you need to submit your Free Code Camp certificate to get your 🟩🟩 Green Belt. [You can see the requirements for each belt here](https://thecsharpacademy.com/dashboard/roadmap). 

🔍For future projects I highly recommend you learn about the [DRY Principle (Don't Repeat Yourself) ](https://www.thecsharpacademy.com/article/30006/dry-principle-csharp). It's the most important challenge in this project. You should be able to have all games using just one method.🤓.

📚I also recommend you go through our [Object Oriented Programming course](https://www.thecsharpacademy.com/course/1/article/1/500000/false) to increase your ability to write cleaner and more maintainable code.

✋🏻Looking forward to seeing your next projects!

**Pull request closed without merging**
