### PR TITLE
Finish!

### PR DESCRIPTION
**Pull request by Mattias1610**
Thanks!

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Mattias1610 Could you please the errors showing in Code Analysis? 😁

**Review by Mattias1610 — COMMENTED** [review]
I fixed the errors!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Mattias1610 Thanks for submitting! It works great, but you forgot one requirement. You need to complete it before approval: 

image

➡️Also, try to call methods for each game (or ideally one method for all games), from your switch statement, so it's more readable. This is optional but it would be good practice.

➡️And finally and also optionally, I recommend you complete the challenges 🤓

**Review by Mattias1610 — COMMENTED** [review]
I think it's done

**Comment by TheCSharpAcademy** [comment]
@Mattias1610  Project approved! 😄✅ It's a shame you didn't complete the challenges this time. 😟 It's always a good use of your time! It's great that you used just one method for all games as well. 👌🏻

And congratulations! You got your green belt!! 🟩🟩

For the future please make sure you remove unnecessary comments and unused code:
image

image

🧑Oh and if possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

**Pull request closed without merging**
