### PR TITLE
finished project basic

### PR DESCRIPTION
**Pull request by Johann-cyber**
I will update and add the challange function later on.

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@Johann-cyber Have you submitted this project in the [Academy's dashboard](https://thecsharpacademy.com/dashboard/submit-project)? I can't see it there. 😟

**Comment by TheCSharpAcademy** [comment]
@Johann-cyber  Hi! Thanks for submitting! It looks like your project was already a repository itself so it was picked up as a subfolder. You can see what files were recognized by git in the "Filers Changed" tab: 

image

To fix this, remove the .git folder from inside your project folder (not the academy's folder), commit again and push 😁 Let me know if you have questions

**Comment by Johann-cyber** [comment]
I've deleted the .git folder. 
There is still the .github folder. I haven't deleted that one

**Comment by TheCSharpAcademy** [comment]
@Johann-cyber Could you please create another PR without the .git folder? You might need to clone the repo again and move your project into it.

**Comment by TheCSharpAcademy** [comment]
@Johann-cyber I'm archiving the project in the dashboard. Feel free to resubmit when you're ready 😊

**Pull request closed without merging**
