### PR TITLE
Initial submission for code review.

### PR DESCRIPTION
**Pull request by cyanitol**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@cyanitol Hi there! Thanks for submitting. At the moment your code doesn't compile. Please update and commit a working app so I can review 😁

image

**Comment by cyanitol** [comment]
Oh, that is embarrassing.  Sorry about that!  Fixed some things found by Codacy and didn't realize I introduced a compile time error.  All fixed and tested now.

**Comment by TheCSharpAcademy** [comment]
@cyanitol Well done! Project approved! 😁 Neat and tidy. I like that you used one method for all games. 

To make it follow Clean principles a bit more I'd outsource validation to a different method. You want your methods to be as lean as possible, doing just one thing when feasible. 

Looking forward to seeing your next project! 👏🏻👏🏻👏🏻

**Comment by cyanitol** [comment]
Thank you for the kinds words and feedback.  Look forward to the rest of the Academy!

**Pull request closed without merging**
