### PR TITLE
Ohshies.MathGame codereview

### PR DESCRIPTION
**Pull request by ohshie**
tbh, i have no idea why my naming convention is different. It took me way to long to understand how to even UPLOAD  TO THE RIGHT FORK if i had created this project with different name prior to forking csarpacademy repo lol.

### CODE REVIEW

**Comment by ohshie** [comment]
(im still not sure whats going o, but looks like new commits are pushed to the right place at least)

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]

**Comment by ohshie** [comment]
Alright, A HUGE thanks to you mr Pablo i just uploaded to mathgame fork manually without wasting my sanity on trying to fight git git :D 
code now includes check to see if result of equation is float and generates a new one if it is. also took my time to rewrite base a bit to use objects/classes more. I think it is better that way? Still havent really utilize props, but im not sure how to do it properly yet.
Whew, that was some fun task. Now ttime to do others

**Comment by summersjs** [comment]
How were you even able to upload this? I have tried multiple times. I am on mac. I somehow over wrote every single file. I managed to save them all but GameEngine. So I spent a few hours rebuilding it. Now, I lost my Program.cs.

**Comment by ohshie** [comment]
> How were you even able to upload this? I have tried multiple times. I am on mac. I somehow over wrote every single file. I managed to save them all but GameEngine. So I spent a few hours rebuilding it. Now, I lost my Program.cs.

i got stuck on finding out that there is not "elegant" way to sync git to my own repo and forked csharpacademy mathgame repo at the same time. It would not let me just pull and push my own changes and would force me to push/pull whole fork repo onto my pc and onto my own repository. So Pablo recommended me to push manually through github website which is exactly what i did here.
i just uploaded my whole project folder onto my fork of csharpacademy mathgame and for my own repo i used standard git push

**Comment by summersjs** [comment]
Thank you! I feel like there is been some progress made. I at least see that I added some files

**Pull request merged**
