### PR TITLE
starting project

### PR DESCRIPTION
**Pull request by Mo3ses**
starting the project today I hope to deliver by the end of the day

### CODE REVIEW

**Comment by Mo3ses** [comment]
added the 4 basics operations, added menu to choose the operations, division dividends go from 0 to 100

**Comment by TheCSharpAcademy** [comment]
@Mo3ses Hello! I can't see this project on the academy's dashboard. Could you please submit it?

**Comment by Mo3ses** [comment]
I forgot the dashboard I just sent it + one more commit going to challenges!

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
Well done on completing the project! There's just one thing that you need to modify. Divisions that DON'T result in integers shouldn't be presented to the users, as per requirement 2.

image


image

**Comment by TheCSharpAcademy** [comment]
@Mo3ses Also the qualified name of the classes derived from System isn't necessary: 
image

**Comment by Mo3ses** [comment]
I improved the code a little and made the change, going to challenges

**Pull request merged**
