### PR TITLE
MathGame console project finished

### PR DESCRIPTION
**Pull request by FarSM**
Learning by projects is really the way to go, it kept me hooked after being unable to focus for months now! Thank you! Please review my code

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@FarSM Hey there! Thanks for submitting your project! 
It looks like your project was already a repository. If that happens, it doesn't get picked up by the parent repository. It's interpreted as a "submodule". To fix it, you'll need to remove the .git folder from INSIDE your project and commit it again. Also your folder should be ProjectName.YourGithubAlias. Thank you!

image

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@FarSM Looks like it's still a submodule? 
Could you please send me the link to your repository in your github? I'll review it anyways

image

**Comment by FarSM** [comment]
I will look into the repository/submodule part of github, I need to understand it better. For now, my project link , Do review.
https://github.com/FarSM/MathGame

**Comment by TheCSharpAcademy** [comment]
> I will look into the repository/submodule part of github, I need to understand it better. For now, my project link , Do review. https://github.com/FarSM/MathGame

I think your repo is marked as private 😊
image

**Comment by FarSM** [comment]
Changed the repo to public. Learning so many little things here. Thanks!

**Comment by TheCSharpAcademy** [comment]
@FarSM Ok, I've reviewed it, well done. I'm not super strict on the first project, and also this wasn't a requirement, but I was able to break it by inputting a string when you're checking for an int. You could validate it with int.TryParse() 

image

**Pull request closed without merging**
