### PR TITLE
Lonchanick.MathGame

### PR DESCRIPTION
**Pull request by lonchanick**
done

### CODE REVIEW

**Comment by broki1** [comment]
Please fix the Codacy error before I review the code. You can find instructions on this in the following article: https://www.thecsharpacademy.com/article/52/code-reviews

If you have any questions, feel free to reply to this comment or reach out on the C# Academy Discord! :)

**Comment by lonchanick** [comment]
Codacy issues fixed!

**Comment by broki1** [comment]
Please add a check to make sure the user doesn't try to divide by zero. :)

**Comment by lonchanick** [comment]
Divided by zero fixed!

**Comment by broki1** [comment]
Approved, good job! Closed the pull request.

**Pull request closed without merging**
