### PR TITLE
finished the project

### PR DESCRIPTION
**Pull request by jakized**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@jakized Hi there! Thanks for submitting! I'm afraid what you've designed isn't a game, but a calculator.

The game should consist of the program presenting a question to the user, say 9 + 8, or 9/3 (keeping in mind it shouldn't present equations that result in non integers), the user should provide the answer, which will be assessed by the program 😄 There's a video with a solution in the project page. Let me know if you have questions.

Oh and if possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

**Comment by TheCSharpAcademy** [comment]
@jakized Let me know if you need help!

**Comment by jakized** [comment]
Hi! @TheCSharpAcademy,

Thank you so much  for your feedback! I have watched the video now, everything clear 😄

**Comment by TheCSharpAcademy** [comment]
@jakized  Project approved! 😄✅ It's a shame you didn't complete the challenges this time. 😟 It's always a good use of your time!  

Oh and if possible join our Discord Community and add your username [to your profile](https://thecsharpacademy.com/dashboard/profile) so you can be part of the community as well. 😁

Looking forward to seeing your next projects! 😄

**Pull request closed without merging**
